# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\GitHub\fssp_api\window_main.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(591, 332)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox_region = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_region.setGeometry(QtCore.QRect(10, 10, 241, 61))
        self.groupBox_region.setObjectName("groupBox_region")
        self.lineEdit_region_filename = QtWidgets.QLineEdit(self.groupBox_region)
        self.lineEdit_region_filename.setGeometry(QtCore.QRect(10, 20, 221, 21))
        self.lineEdit_region_filename.setObjectName("lineEdit_region_filename")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(10, 80, 571, 241))
        self.textBrowser.setObjectName("textBrowser")
        self.groupBox_results = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_results.setGeometry(QtCore.QRect(260, 10, 241, 61))
        self.groupBox_results.setObjectName("groupBox_results")
        self.lineEdit_results_filename = QtWidgets.QLineEdit(self.groupBox_results)
        self.lineEdit_results_filename.setGeometry(QtCore.QRect(10, 20, 221, 21))
        self.lineEdit_results_filename.setObjectName("lineEdit_results_filename")
        self.pushButton_search = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_search.setGeometry(QtCore.QRect(510, 20, 71, 21))
        self.pushButton_search.setStyleSheet("background-color: rgb(255, 206, 206);")
        self.pushButton_search.setObjectName("pushButton_search")
        self.pushButton_update = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_update.setGeometry(QtCore.QRect(510, 50, 71, 21))
        self.pushButton_update.setStyleSheet("background-color: rgb(212, 255, 212);")
        self.pushButton_update.setObjectName("pushButton_update")
        MainWindow.setCentralWidget(self.centralwidget)
        self.action_6 = QtWidgets.QAction(MainWindow)
        self.action_6.setObjectName("action_6")
        self.action_7 = QtWidgets.QAction(MainWindow)
        self.action_7.setObjectName("action_7")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox_region.setTitle(_translate("MainWindow", "excel-файл, список людей и регионов"))
        self.lineEdit_region_filename.setText(_translate("MainWindow", "debtors"))
        self.groupBox_results.setTitle(_translate("MainWindow", "excel-файл, для записи результатов"))
        self.lineEdit_results_filename.setText(_translate("MainWindow", "debtors_results"))
        self.pushButton_search.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.pushButton_search.setText(_translate("MainWindow", "Search"))
        self.pushButton_update.setText(_translate("MainWindow", "Update"))
        self.action_6.setText(_translate("MainWindow", "Создать новую базу"))
        self.action_7.setText(_translate("MainWindow", "Загрузить"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
