# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\GitHub\fssp_api\window_main.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(262, 351)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox_search = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_search.setGeometry(QtCore.QRect(10, 10, 241, 81))
        self.groupBox_search.setObjectName("groupBox_search")
        self.lineEdit_find_filename = QtWidgets.QLineEdit(self.groupBox_search)
        self.lineEdit_find_filename.setGeometry(QtCore.QRect(10, 20, 221, 21))
        self.lineEdit_find_filename.setObjectName("lineEdit_find_filename")
        self.lineEdit_find_status = QtWidgets.QLineEdit(self.groupBox_search)
        self.lineEdit_find_status.setEnabled(False)
        self.lineEdit_find_status.setGeometry(QtCore.QRect(60, 50, 91, 20))
        self.lineEdit_find_status.setMouseTracking(True)
        self.lineEdit_find_status.setObjectName("lineEdit_find_status")
        self.pushButton_clear = QtWidgets.QPushButton(self.groupBox_search)
        self.pushButton_clear.setGeometry(QtCore.QRect(10, 50, 41, 21))
        self.pushButton_clear.setObjectName("pushButton_clear")
        self.pushButton_search = QtWidgets.QPushButton(self.groupBox_search)
        self.pushButton_search.setGeometry(QtCore.QRect(160, 50, 71, 21))
        self.pushButton_search.setObjectName("pushButton_search")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(10, 100, 241, 241))
        self.textBrowser.setObjectName("textBrowser")
        MainWindow.setCentralWidget(self.centralwidget)
        self.action_6 = QtWidgets.QAction(MainWindow)
        self.action_6.setObjectName("action_6")
        self.action_7 = QtWidgets.QAction(MainWindow)
        self.action_7.setObjectName("action_7")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox_search.setTitle(_translate("MainWindow", "Введите имя файла excel"))
        self.lineEdit_find_filename.setText(_translate("MainWindow", "debtor_list"))
        self.lineEdit_find_status.setText(_translate("MainWindow", "Select files"))
        self.pushButton_clear.setText(_translate("MainWindow", "Clear"))
        self.pushButton_search.setText(_translate("MainWindow", "Search"))
        self.action_6.setText(_translate("MainWindow", "Создать новую базу"))
        self.action_7.setText(_translate("MainWindow", "Загрузить"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
